# Generated by Django 5.0.4 on 2024-07-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
    ]
