# Generated by Django 5.0.4 on 2024-07-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
    ]
