# Generated by Django 5.0.4 on 2024-07-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
    ]
